### ISSUE TITLE
Error when enabling SMTP

### ISSUE THREAD

**Issue by sukidhar** [maennchen/email_checker#20]
```
** (UndefinedFunctionError) function Socket.TCP.connect!/3 is undefined (module Socket.TCP is not available)
    Socket.TCP.connect!("gmail-smtp-in.l.google.com", 25, [packet: :line, timeout: :infinity])
    (email_checker 0.2.4) lib/email_checker/check/smtp.ex:66: EmailChecker.Check.SMTP.smtp_reply/1
    (email_checker 0.2.4) lib/email_checker/check/smtp.ex:32: EmailChecker.Check.SMTP.valid?/2
```

**Comment by mohammedzeglam-pg** [comment]
> ```
> ** (UndefinedFunctionError) function Socket.TCP.connect!/3 is undefined (module Socket.TCP is not available)
>     Socket.TCP.connect!("gmail-smtp-in.l.google.com", 25, [packet: :line, timeout: :infinity])
>     (email_checker 0.2.4) lib/email_checker/check/smtp.ex:66: EmailChecker.Check.SMTP.smtp_reply/1
>     (email_checker 0.2.4) lib/email_checker/check/smtp.ex:32: EmailChecker.Check.SMTP.valid?/2
> ```
it is not worthing to enable it it take a lot of time but the problem happen because of this https://github.com/jshmrtn/email_checker/blob/04a6e76e8575c819ccd57509f0fb1f2343ec7362/mix.exs#L64

or maybe because of this
https://github.com/jshmrtn/email_checker/blob/04a6e76e8575c819ccd57509f0fb1f2343ec7362/README.md?plain=1#L28

**Comment by maennchen** [comment]
Socket is an optional dependency. Install it if you want to use the SMTP check.
